# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - skip: true
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
