name: Release

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: "The version to publish (patch, minor, current)"
        required: true

permissions:
  contents: write

jobs:
  authorize:
    name: Authorize
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.actor }} permission check to do a release
        uses: "lannonbr/repo-permission-check-action@2.0.2"
        with:
          permission: "write"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [authorize]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17'
          cache: true

      - name: Run tests
        run: go test -v ./...

      - name: Get new version
        id: new_version
        uses: anothrNick/github-tag-action@1.40.0
        if: ${{ github.event.inputs.packageVersion != 'current' }}
        env:
          DRY_RUN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: ${{ github.event.inputs.packageVersion }}

      - name: Update SdkVersion in constants.go
        if: ${{ github.event.inputs.packageVersion != 'current' }}
        run: |
          sed -i -e 's/\(SdkVersion\s*=\s*\)"[^"]*"/\1"${{ steps.new_version.outputs.new_tag }}"/' ./amplitude/constants/constants.go
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -am "v${{ steps.new_version.outputs.new_tag }}"
          git push

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.40.0
        if: ${{ github.event.inputs.packageVersion != 'current' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: ${{ github.event.inputs.packageVersion }}

      - name: Release version
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Go Module Index
        run: curl "https://proxy.golang.org/github.com/amplitude/analytics-go/@v/$(git describe HEAD --tags --abbrev=0).info"
